class DebugConstant {

static const List<String> projectTypes = [
    'Flutter',
    'Android (Kotlin)',
    'Android (Java)',
    'iOS (Swift)',
    'iOS (Objective-C)',
    'React',
    'React Native',
    'Next.js',
    'Vue.js',
    'Angular',
    'Node.js',
    'Express.js',
    'NestJS',
    'Laravel',
    'Django',
    'Flask',
    'FastAPI',
    'ASP.NET Core',
    'Spring Boot',
    'Ruby on Rails',
    'PHP',
    'Python',
    'Java',
    'C#',
    'C++',
    'Go',
    'Rust',
    'Kotlin',
    'Swift',
    'Electron',
    'Desktop Application',
    'Web Application',
    'Mobile Application',
    'API',
    'CLI Tool',
    'AI / Machine Learning',
    'Data Science',
    'Game Development',
    'Unity',
    'Unreal Engine',
    'Blockchain',
    'IoT',
    'Other',
  ];
  static const technologies = [
    'Flutter',
    'Dart',
    'Firebase',
    'Bloc',
    'Cubit',
    'Provider',
    'Riverpod',
    'GetX',
    'Dio',
    'HTTP',
    'SQLite',
    'Hive',
    'Shared Preferences',
    'Supabase',
    'REST API',
    'GraphQL',
    'Gemini AI',
    'OpenAI',
    'Go Router',
    'Firebase Auth',
    'Cloud Firestore',
  ];


}